#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64
"username/password@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl12c)))" <<EOF

DROP TABLE SALES_EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE SALES_TRANSACTION CASCADE CONSTRAINTS;
DROP TABLE ICE_CREAM_STOCK CASCADE CONSTRAINTS;
DROP TABLE RESUPPLY_ORDER CASCADE CONSTRAINTS;
DROP TABLE FACTORY CASCADE CONSTRAINTS;
DROP TABLE ICE_CREAM_FLAVOURS CASCADE CONSTRAINTS;
DROP TABLE FLAVOUR_INGREDIENTS CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTS CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTS_STOCK CASCADE CONSTRAINTS;
exit;
EOF